### ISSUE TITLE
기획서 분석

### ISSUE THREAD

**Issue by reesekimm** [codesquad-member-2020/vm-4#1]

**Comment by reesekimm** [comment]
- 요구사항 파악 후 전체적인 프로젝트 구조를 논의
- 현시점에서의 backlog 및 sprint 작성 (3/11 수요일에 업데이트 예정)

**Comment by 77unny** [comment]
MVC 패턴 사용
- View : 상품화면 / 상품선택화면 / 지갑화면
- Model : 상품리스트 / 지갑
- Controller : 기능 & 옵저버

**Comment by 77unny** [comment]
express모듈을 사용하여 api data
