### ISSUE TITLE
HTML / CSS UI 구현

### ISSUE THREAD

**Issue by 77unny** [codesquad-member-2020/vm-4#2]

**Comment by 77unny** [comment]
##### 디렉토리 구조

- servrer 
  - api data
  - server 
- src
  - controllers : 기능 Function 관련 로직 담당
  - models : 아이템 리스트 / 지갑(wallet&money) 데이터 담당
  - views : 아이템 리스트 뷰 / 선택 및 현황판 뷰 / 지갑(wallet) 뷰 담당
- style 
  - style 담당 (scss&css)
- main.js
- index.html

**Comment by 77unny** [comment]
##### 마크업 ID 및 class 구조

- app 
  - vending-machine : 자판기 담당
    - panel-items : 아이템리스트를 보여주는 패널
    - panel-state : 자판기 상태들을 담당파는 패널
      - state-money : 투입금액&남은금액 표시
      - state-number : 아이템 선택 번호 표시
      - state-message : 진행상태표시 메시지창 
  - wallet
    - wallet-state : 지갑의 돈의 상태들 표시
    - wallet-total : 총 돈의 값을 표시

**Comment by 77unny** [comment]
<img width="771" alt="스크린샷 2020-03-09 오후 10 20 37" src="https://user-images.githubusercontent.com/44539224/76217925-a9944f00-6256-11ea-8034-9940b1bd5d0c.png">

자판기 UI 부분 임시 스타일링

**Comment by 77unny** [comment]
임시 구현 완료
- 자판기 UI / 지갑 UI

**Comment by crongro** [comment]
스타일 이쁘네요.
