### ISSUE TITLE
브랜치 변경? dev → develop

### ISSUE THREAD

**Issue by reesekimm** [codesquad-member-2020/vm-4#43]
@baekCode 
Merge pull request 버튼 하나 잘못 눌렀다가 대참사가 일어났습니다... 미안해요ㅠㅠㅠ
정황 및 수습내용은 [여기](https://github.com/codesquad-memeber-2020/vm-4/pull/42)서 확인 가능합니당...
혹시 이전 커밋로그 포함해서 dev -> master로 PR 되게 하는 방법 아시면 알려주세용ㅠ

**Comment by 77unny** [comment]
헐! ㅠㅠ 엄청 고생하셨겠어요! ㅎㅎ 
저도 한번 알아보겠습니다.

**Comment by 77unny** [comment]
구글링 및 젤로 한테 확인해보니 dev에서 대부분 충돌이 일어날 경우 그렇다는 말도있어서 일단 pr 보내보고 충돌나는 부분 해결해서 하면된다는데 한번 pr 보내 볼께요

**Comment by 77unny** [comment]
controller.js 충돌이있어요! ㅎㅎ

**Comment by reesekimm** [comment]
> controller.js 충돌이있어요! ㅎㅎ

혹시 일을 더 키우게 될까봐 PR 안날렸는데 충돌이 원인이었다니 다행이에요!
