### ISSUE TITLE
1주차 피드백 vendingMachine & wallet 공통 반영 사항

### ISSUE THREAD

**Issue by reesekimm** [codesquad-member-2020/vm-4#47]
금일 크롱의 1주차 피드백 내용 중 **VendingMachine과 Wallet 작업시 공통적으로 반영되어야 할 사항**을 이슈로 정리하여 남깁니다.

@baekCode  확인 부탁드려요!~

1. https://github.com/codesquad-memeber-2020/vm-4/pull/42#discussion_r393399916
-> **controller.js** 이벤트 바인딩 메소드 이름 수정

<br />

2. https://github.com/codesquad-memeber-2020/vm-4/pull/42#discussion_r393402856
-> **observable.js**  type에서 'on' 지우고 맨 앞글자 소문자로 치환
     - onLoad  -> loadData
     - onPurchase -> purchaseItem
     - onInputMoney  -> inputMoney

<br />

3. https://github.com/codesquad-memeber-2020/vm-4/pull/42#discussion_r393405109
-> **template.js** 를 기존 /util 에서 /views 디렉토리로 이동

**Comment by 77unny** [comment]
1. controller.js 이벤트 메소드 수정
onClick## 메소드 itemClickHandler / walletClickHandler 메소드 수정

2. observable.js 'on' 제거
옵저버 구독자 부분도 제거 완료

3. template.js 디렉토리 변경
