### ISSUE TITLE
구체적인 flow 논의

### ISSUE THREAD

**Issue by reesekimm** [codesquad-member-2020/vm-4#5]
(3/10 화요일 저녁) skeleton code 작성 후 hangout으로 얘기해보기

**Comment by 77unny** [comment]
제가 일단 임시로 생객해본 디렉토리 구조입니다. 확인 부탁드러용 @reesekimm 

##### 디렉토리 구조

- servrer 
  - api data
  - server 
- src
  - controllers : 기능 Function 관련 로직 담당
  - models : 아이템 리스트 / 지갑(wallet&money) 데이터 담당
  - views : 아이템 리스트 뷰 / 선택 및 현황판 뷰 / 지갑(wallet) 뷰 담당
- style 
  - style 담당 (scss&css)
- main.js
- index.html

**Comment by reesekimm** [comment]
확인했습니다!
내일 같이 얘기해봐요:)
